### ISSUE TITLE
When i copy over text with commas, they are not recognized and split into multiple chips

### ISSUE THREAD

**Issue by maheedhar1305** [blackjackkent/react-multivalue-text-input#34]
If I type value1, value2 in the field manually. value1 and value2 are added to the items list as individually. 

allItems = ["value1", "value2"]
allItems.length == 2

If I copy over the text "value1, value2" from a different file into the field and press ENTER, it becomes added as a single string

allItems = ["value1, value2"]
allItems.length == 1

Can you please let me know how to fix this issue? I tried parsing this inside the onItemAdded function but that does not reflect in the UI eventhough I am able to retrieve the individual strings upon form submission.

**Comment by blackjackkent** [comment]
Hey, thanks for letting me know about this! That's a good bug catch; let me see if I can work on a fix for it. :)

**Comment by maheedhar1305** [comment]
Thank you so much. I was going through the source code and the fix seemed
straight forward by adding an even listener for the onPaste event which
would split strings based on the charCodes property and add to the list of
values. Would you be open to reviewing a PR if I were to submit one?

P.S :  am a react noob so i will let you know if i hit a roadblock

**Comment by blackjackkent** [comment]
Sure, if you'd like! Go for it. :)

Def let me know if you get stuck; to be honest, this project is a little out of date so I probably have some housekeeping I need to do on it. 😬 But yeah, it should be a quick fix once you're up and running.

**Comment by blackjackkent** [comment]
On closer investigation, I realized I left the `development` branch in the middle of a major-version level refactor. :P So I will work on getting that cleaned up within the next few days as well. In the meantime you should be able to work your PR off the `production` branch.

**Comment by maheedhar1305** [comment]
I created a PR but I am basically stuck with a new problem now and need your help. Here is the PR with my proposed changes : https://github.com/blackjackkent/react-multivalue-text-input/pull/35

in the onPaste handler I am trying to split the string using the charCode delimiters and trying to iteratively add them all by calling the handleItemAdd multiple times but it only renders it once. What am i doing wrong?

example : If i paste value1, value2, value3 into the text field, I only see value3 pop up as a chip above the field. Not sure why value1 and value2 wont show up.

**Comment by blackjackkent** [comment]
This is really close! Thank you for taking a crack at it. :)

I think, having looked at it more closely, it makes more sense for me to just re-implement this in the major-version refactor I'm doing, since I'm now realizing the changes here are pretty significant (for instance, I'm switching away from `charCodes` in favor of the `e.key` property on React keyboard events). However, I can give a few pointers here just in general since you said you're newish at React. 😄 

a) I think the reason you were encountering weird behavior with this implementation is that you are attempting to call `handleItemAdd` (and therefore `setValues`) multiple times within one render. I will probably lean instead towards creating something like an additional `handleItemsAdd`  function (note the plural) which will handle adding multiple values at once in a single call to `setValues`, which `handlePaste` can then use.

b) On line 96 you are declaring a `values` constant which masks the `values` state variable from line 61. (Same with your `value` variable on line 97 masking the `value` state variable from line 62.) In this case, I think the code should work the same regardless, but it's good practice not to stack variable names on top of each other in the same scope.

I will let you know when I have the refactor complete - would you like to have the opportunity to take another stab at it when that's done, building off the new code? Or would you like me to go ahead and complete the fix as part of that release? I don't mind either way, if it's a good learning opportunity for you. :)

**Comment by maheedhar1305** [comment]
Thank you so much for walking me through this, this is really helpful. These sound like obvious things I should know but my experience has been very backend heavy and all this is new to me, so I appreciate your time very much. 

I did have a suspicion that invoking a function multiple times within one event might be creating some issues but I couldn't say which part, so this helps. Following along your line of thought,  creating a new handleItemsAdd function would also then require an onItemsAdded (plural) function to be added as an input parameter for the MultipleValueTextInput component right? or would i be able to invoke the existing onItemAdded function multiple items from within handleItemsAdd? 

Its great to know you are working on a major version refactor. Do you know what the timeline is for that release? I would love to have the opportunity to take another stab at it. But also, if you suspect that is going to take some time, is it ok if I take another stab within the current version and add a new handleItemsAdded function in the meanwhile, so that I can use your component in my application?

**Comment by blackjackkent** [comment]
Hrmdehrm. That is a good question re: changing the inputs from the user side. To be honest, I might have a better answer for it once we've settled on the internal implementation - my strategy with React often involves figuring out the smaller bits first and then figuring out how to build on top of them.

The big refactor (which was originally mostly about implementing typescript support but has now expanded to a bunch of other cleanup and changes as well, including a better developer experience) was actually mostly done a number of months ago and then I just got sort of distracted and forgot about it. 😅 But you arriving with questions and interest has put me back on it *and* I have free time right now because of the holidays, so I'm going to commit to getting it done and ready to go by the end of the first week of January. :)

And no problem re: the answering questions and such! I do a lot of helping new devs with Javascript stuff so I'm always happy to. (Shameless self promo - if you're looking for help while learning front-end stuff, I have a discord community that I run for gaming and programming chat that's linked in my profile; you're welcome to join that and hang out to ask questions if you'd like. :) )

In any event - TLDR feel free to keep going with your implementation if you'd like if these tips point you in the right direction, but also I will try to have the cleaned up code ready within the next week or so. :)

**Comment by maheedhar1305** [comment]
Hey I think I have made a breakthrough. Your idea to create a new handleItemsAdd function worked beautifully and I didnt have to create a new user defined function and was able to use the existing onItemAdded and call it multiple times as long as i rendered the state variable only once. That seemed to do the trick for me and works well. Do you mind taking a look at the PR again? I just pushed my changes again. If you could create a patch version for me that I can use it in my application while waiting for your major version, that would be great. I could use the patch as a stop gap while I wait for your major release.

P.S I will definitely join the discord community thanks for pointing me to it, I need all the help I can get at this point :)

**Comment by maheedhar1305** [comment]
This was resolved here : https://github.com/blackjackkent/react-multivalue-text-input/pull/37

**Comment by maheedhar1305** [comment]
https://github.com/blackjackkent/react-multivalue-text-input/releases/tag/v2.1.0
